// <auto-generated />
using System;
using LogJammer.Engine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogJammer.Engine.Migrations
{
    [DbContext(typeof(LogJammerDbContext))]
    [Migration("20260318131846_InitialV2")]
    partial class InitialV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogJammer.Engine.Data.Entities.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionConfig")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastPolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataSources");
                });

            modelBuilder.Entity("LogJammer.Engine.Data.Entities.DrainState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("SerializedState")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId")
                        .IsUnique();

                    b.ToTable("DrainStates");
                });

            modelBuilder.Entity("LogJammer.Engine.Data.Entities.LogPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClusterId")
                        .HasColumnType("integer");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SampleMessage")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.ToTable("LogPatterns");
                });

            modelBuilder.Entity("LogJammer.Engine.Data.Entities.PatternBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AvgCount")
                        .HasColumnType("double precision");

                    b.Property<int>("HourOfWeek")
                        .HasColumnType("integer");

                    b.Property<Guid>("PatternId")
                        .HasColumnType("uuid");

                    b.Property<double>("StdDevCount")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PatternId", "HourOfWeek")
                        .IsUnique();

                    b.ToTable("PatternBaselines");
                });

            modelBuilder.Entity("LogJammer.Engine.Data.Entities.PatternOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PatternId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("WindowEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatternId", "WindowStart")
                        .IsUnique();

                    b.ToTable("PatternOccurrences");
                });

            modelBuilder.Entity("LogJammer.Engine.Data.Entities.DrainState", b =>
                {
                    b.HasOne("LogJammer.Engine.Data.Entities.DataSource", "DataSource")
                        .WithOne("DrainState")
                        .HasForeignKey("LogJammer.Engine.Data.Entities.DrainState", "DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("LogJammer.Engine.Data.Entities.LogPattern", b =>
                {
                    b.HasOne("LogJammer.Engine.Data.Entities.DataSource", "DataSource")
                        .WithMany("Patterns")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("LogJammer.Engine.Data.Entities.PatternBaseline", b =>
                {
                    b.HasOne("LogJammer.Engine.Data.Entities.LogPattern", "Pattern")
                        .WithMany("Baselines")
                        .HasForeignKey("PatternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pattern");
                });

            modelBuilder.Entity("LogJammer.Engine.Data.Entities.PatternOccurrence", b =>
                {
                    b.HasOne("LogJammer.Engine.Data.Entities.LogPattern", "Pattern")
                        .WithMany("Occurrences")
                        .HasForeignKey("PatternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pattern");
                });

            modelBuilder.Entity("LogJammer.Engine.Data.Entities.DataSource", b =>
                {
                    b.Navigation("DrainState");

                    b.Navigation("Patterns");
                });

            modelBuilder.Entity("LogJammer.Engine.Data.Entities.LogPattern", b =>
                {
                    b.Navigation("Baselines");

                    b.Navigation("Occurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
