// <auto-generated />
using System;
using LogJammer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace LogJammer.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LogJammerDbContext))]
    partial class LogJammerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogJammer.Core.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<double>("ActualValue")
                        .HasColumnType("double precision")
                        .HasColumnName("actual_value");

                    b.Property<int>("ConsecutiveBelowThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_below_threshold");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("KnownErrorId")
                        .HasColumnType("uuid")
                        .HasColumnName("known_error_id");

                    b.Property<DateTime?>("LastNotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_notified_at");

                    b.Property<int>("NotificationCount")
                        .HasColumnType("integer")
                        .HasColumnName("notification_count");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("ThresholdType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("threshold_type");

                    b.Property<double>("ThresholdValue")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("KnownErrorId");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("LogJammer.Core.Entities.ClassificationConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("classification_config", (string)null);
                });

            modelBuilder.Entity("LogJammer.Core.Entities.ClassificationQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("KnownErrorId")
                        .HasColumnType("uuid")
                        .HasColumnName("known_error_id");

                    b.Property<bool>("Reviewed")
                        .HasColumnType("boolean")
                        .HasColumnName("reviewed");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("SuggestedTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_tags");

                    b.HasKey("Id");

                    b.HasIndex("KnownErrorId");

                    b.HasIndex("Reviewed")
                        .HasFilter("reviewed = false");

                    b.ToTable("classification_queue", (string)null);
                });

            modelBuilder.Entity("LogJammer.Core.Entities.CorrelatedSpikeAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AlertIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alert_ids");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer")
                        .HasColumnName("group_count");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.ToTable("correlated_spike_alerts", (string)null);
                });

            modelBuilder.Entity("LogJammer.Core.Entities.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AdapterType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("adapter_type");

                    b.Property<string>("ConnectionConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("connection_config");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PollIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("poll_interval_seconds");

                    b.Property<int>("SamplingBudget")
                        .HasColumnType("integer")
                        .HasColumnName("sampling_budget");

                    b.Property<string>("SchemaMapping")
                        .HasColumnType("jsonb")
                        .HasColumnName("schema_mapping");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("LogJammer.Core.Entities.ErrorOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("KnownErrorId")
                        .HasColumnType("uuid")
                        .HasColumnName("known_error_id");

                    b.Property<double?>("SampleRatio")
                        .HasColumnType("double precision")
                        .HasColumnName("sample_ratio");

                    b.Property<DateTime>("WindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Id");

                    b.HasIndex("KnownErrorId", "WindowStart");

                    b.ToTable("error_occurrences", (string)null);
                });

            modelBuilder.Entity("LogJammer.Core.Entities.ErrorTag", b =>
                {
                    b.Property<Guid>("KnownErrorId")
                        .HasColumnType("uuid")
                        .HasColumnName("known_error_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAutoAssigned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_assigned");

                    b.HasKey("KnownErrorId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("error_tags", (string)null);
                });

            modelBuilder.Entity("LogJammer.Core.Entities.FingerprintAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FingerprintHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint_hash");

                    b.Property<Guid>("KnownErrorId")
                        .HasColumnType("uuid")
                        .HasColumnName("known_error_id");

                    b.HasKey("Id");

                    b.HasIndex("FingerprintHash")
                        .IsUnique();

                    b.HasIndex("KnownErrorId");

                    b.ToTable("fingerprint_aliases", (string)null);
                });

            modelBuilder.Entity("LogJammer.Core.Entities.FingerprintConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_name");

                    b.Property<bool>("NormalizeBeforeHash")
                        .HasColumnType("boolean")
                        .HasColumnName("normalize_before_hash");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.ToTable("fingerprint_configs", (string)null);
                });

            modelBuilder.Entity("LogJammer.Core.Entities.KnownError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<Vector>("EmbeddingVector")
                        .HasColumnType("vector(384)")
                        .HasColumnName("embedding_vector");

                    b.Property<string>("FingerprintHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint_hash");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("OccurrenceWindows")
                        .HasColumnType("jsonb")
                        .HasColumnName("occurrence_windows");

                    b.Property<string>("RepresentativeMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("representative_message");

                    b.Property<string>("RepresentativeStackTrace")
                        .HasColumnType("text")
                        .HasColumnName("representative_stack_trace");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<long>("TotalOccurrences")
                        .HasColumnType("bigint")
                        .HasColumnName("total_occurrences");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("FingerprintHash")
                        .IsUnique();

                    b.ToTable("known_errors", (string)null);
                });

            modelBuilder.Entity("LogJammer.Core.Entities.SpikeDetectionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid?>("KnownErrorId")
                        .HasColumnType("uuid")
                        .HasColumnName("known_error_id");

                    b.Property<int>("LookbackMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("lookback_minutes");

                    b.Property<string>("ThresholdType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("threshold_type");

                    b.Property<double>("ThresholdValue")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WindowMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("window_minutes");

                    b.HasKey("Id");

                    b.HasIndex("KnownErrorId")
                        .IsUnique();

                    b.ToTable("spike_detection_rules", (string)null);
                });

            modelBuilder.Entity("LogJammer.Core.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("TagType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tag_type");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("LogJammer.Core.Entities.TagCentroid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Vector>("CentroidVector")
                        .HasColumnType("vector(384)")
                        .HasColumnName("centroid_vector");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TagId")
                        .IsUnique();

                    b.ToTable("tag_centroids", (string)null);
                });

            modelBuilder.Entity("LogJammer.Core.Entities.UserOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("KnownErrorId")
                        .HasColumnType("uuid")
                        .HasColumnName("known_error_id");

                    b.Property<string>("OverrideData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("override_data");

                    b.Property<string>("OverrideType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("override_type");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("KnownErrorId");

                    b.ToTable("user_overrides", (string)null);
                });

            modelBuilder.Entity("LogJammer.Core.Entities.Alert", b =>
                {
                    b.HasOne("LogJammer.Core.Entities.KnownError", "KnownError")
                        .WithMany("Alerts")
                        .HasForeignKey("KnownErrorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnownError");
                });

            modelBuilder.Entity("LogJammer.Core.Entities.ClassificationQueueItem", b =>
                {
                    b.HasOne("LogJammer.Core.Entities.KnownError", "KnownError")
                        .WithMany()
                        .HasForeignKey("KnownErrorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnownError");
                });

            modelBuilder.Entity("LogJammer.Core.Entities.CorrelatedSpikeAlert", b =>
                {
                    b.HasOne("LogJammer.Core.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("LogJammer.Core.Entities.ErrorOccurrence", b =>
                {
                    b.HasOne("LogJammer.Core.Entities.KnownError", "KnownError")
                        .WithMany("Occurrences")
                        .HasForeignKey("KnownErrorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnownError");
                });

            modelBuilder.Entity("LogJammer.Core.Entities.ErrorTag", b =>
                {
                    b.HasOne("LogJammer.Core.Entities.KnownError", "KnownError")
                        .WithMany("ErrorTags")
                        .HasForeignKey("KnownErrorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogJammer.Core.Entities.Tag", "Tag")
                        .WithMany("ErrorTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnownError");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LogJammer.Core.Entities.FingerprintAlias", b =>
                {
                    b.HasOne("LogJammer.Core.Entities.KnownError", "KnownError")
                        .WithMany("FingerprintAliases")
                        .HasForeignKey("KnownErrorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnownError");
                });

            modelBuilder.Entity("LogJammer.Core.Entities.FingerprintConfig", b =>
                {
                    b.HasOne("LogJammer.Core.Entities.DataSource", "DataSource")
                        .WithMany("FingerprintConfigs")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("LogJammer.Core.Entities.KnownError", b =>
                {
                    b.HasOne("LogJammer.Core.Entities.DataSource", "DataSource")
                        .WithMany("KnownErrors")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("LogJammer.Core.Entities.SpikeDetectionRule", b =>
                {
                    b.HasOne("LogJammer.Core.Entities.KnownError", "KnownError")
                        .WithMany()
                        .HasForeignKey("KnownErrorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("KnownError");
                });

            modelBuilder.Entity("LogJammer.Core.Entities.TagCentroid", b =>
                {
                    b.HasOne("LogJammer.Core.Entities.Tag", "Tag")
                        .WithOne()
                        .HasForeignKey("LogJammer.Core.Entities.TagCentroid", "TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LogJammer.Core.Entities.UserOverride", b =>
                {
                    b.HasOne("LogJammer.Core.Entities.KnownError", "KnownError")
                        .WithMany("UserOverrides")
                        .HasForeignKey("KnownErrorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnownError");
                });

            modelBuilder.Entity("LogJammer.Core.Entities.DataSource", b =>
                {
                    b.Navigation("FingerprintConfigs");

                    b.Navigation("KnownErrors");
                });

            modelBuilder.Entity("LogJammer.Core.Entities.KnownError", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("ErrorTags");

                    b.Navigation("FingerprintAliases");

                    b.Navigation("Occurrences");

                    b.Navigation("UserOverrides");
                });

            modelBuilder.Entity("LogJammer.Core.Entities.Tag", b =>
                {
                    b.Navigation("ErrorTags");
                });
#pragma warning restore 612, 618
        }
    }
}
